<a href="https://colab.research.google.com/github/jackiekuen2/notes-handson-ml-tf/blob/master/ch5_ExerciseQ8_SVMIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LinearSVC vs SVC vs SGDClassifier

In [0]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris['data']
y = iris['target']

In [0]:
X.shape

(150, 4)

In [0]:
y.shape

(150,)

In [0]:
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

In [0]:
C = 5
alpha = 1/(C*len(X))

linsvc_clf = LinearSVC(C=C, loss='hinge', random_state=42)
svm_clf = SVC(kernel='linear', C=C, random_state=42)
sgd_clf = SGDClassifier(loss='hinge', learning_rate='constant', eta0=0.001,
                        alpha=alpha, max_iter=100000, tol=-np.infty, random_state=42)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

linsvc_clf.fit(X_scaled, y)
svm_clf.fit(X_scaled, y)
sgd_clf.fit(X_scaled, y)


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


SGDClassifier(alpha=0.0013333333333333333, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='constant', loss='hinge',
              max_iter=100000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=-inf,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
print('LinearSVC:', linsvc_clf.intercept_, linsvc_clf.coef_)
print('SVC: ', svm_clf.intercept_, svm_clf.coef_)
print('SGD: ', sgd_clf.intercept_, sgd_clf.coef_)

LinearSVC: [-0.9185277  -0.76494797 -3.59059202] [[-0.12688769  0.57417632 -0.87244637 -1.2620236 ]
 [ 0.00324716 -1.00811579  1.93678887 -1.98145019]
 [-0.33110363 -0.69799813  3.07951677  2.78445079]]
SVC:  [-1.47408609 -0.29523178  3.95010556] [[-0.43882206  0.33180056 -0.89190361 -0.92297181]
 [-0.06460811  0.1389477  -0.55334547 -0.55657227]
 [ 0.43512977  0.70980043 -3.3251531  -3.24613868]]
SGD:  [-1.475 -0.768 -3.943] [[-0.43473183  0.33216053 -0.89938196 -0.92135285]
 [ 0.01097908 -1.00649751  1.93983457 -1.98746097]
 [-0.44018429 -0.70655832  3.33513706  3.23187964]]
